### ISSUE TITLE
Wiki: HTTP Status 500 – Internal Server Error

### ISSUE THREAD

**Issue by nickurbanik** [softhsm/SoftHSMv2#695]
Please fix the wiki: I need it to set up opendnssec today if possible!

**Comment by nickurbanik** [comment]
https://wiki.opendnssec.org/bootstrap/selectsetupstep.action gives an impressively long stack trace, but that is not the whole story: at the bottom of the page is written that the full stack trace is in the logs.

**Comment by dmihalcik** [comment]
The link for the wiki, https://wiki.opendnssec.org/display/SoftHSMDOCS, is not resolving for me

**Comment by bjosv** [comment]
Do you still see problems with the wiki? It seems to have worked fine here for a while.
Please feel free to close this issue if you believe it's ok.

**Comment by jschlyter** [comment]
Will be addressed n #765
